# Generated by Django 3.1.7 on 2021-03-03 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='icons',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
