# Generated by Django 3.1.7 on 2021-03-04 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_services_icons'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='department',
            new_name='find_us',
        ),
    ]
